[2020-06-29 10:11:30,059] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 10:11:39,971] [log.py:222] [log:log_response] [WARNING]- Not Found: /auth/
[2020-06-29 10:11:39,973] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 404 37
[2020-06-29 10:12:19,290] [log.py:222] [log:log_response] [WARNING]- Not Found: /auth/
[2020-06-29 10:12:19,292] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 404 37
[2020-06-29 10:46:07,046] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 10:46:07,838] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 10:46:18,219] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 10:46:18,362] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:46:18,364] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:46:31,820] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:46:31,822] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:46:34,108] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:46:34,111] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:46:43,398] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:46:43,400] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:46:46,673] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:46:46,675] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:48:25,990] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 10:48:26,881] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 10:48:27,880] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:48:27,881] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:48:31,945] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:48:31,947] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:48:39,823] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 10:54:48,144] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 10:54:48,149] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 10:54:53,514] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 11:00:46,660] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 11:00:46,849] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 11:00:46,851] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 11:00:53,211] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 11:00:53,223] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 11:00:59,889] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 11:00:59,890] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 11:01:09,328] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 13:59:32,576] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 13:59:38,659] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 13:59:43,334] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 13:59:57,781] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 13:59:57,782] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 13:59:57,814] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=admin&application=monitor&type=menu HTTP/1.1" 301 0
[2020-06-29 13:59:57,814] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=admin&application=monitor&type=button HTTP/1.1" 301 0
[2020-06-29 13:59:57,867] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 13:59:57,868] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 13:59:58,149] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 2
[2020-06-29 13:59:58,163] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 563
[2020-06-29 14:00:06,567] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=asset&type=menu HTTP/1.1" 200 0
[2020-06-29 14:00:06,569] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=asset&type=button HTTP/1.1" 200 0
[2020-06-29 14:00:06,587] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 0
[2020-06-29 14:00:06,602] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 0
[2020-06-29 14:00:06,912] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 60
[2020-06-29 14:00:06,925] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 6014
[2020-06-29 14:03:45,473] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 14:03:46,516] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 14:12:49,346] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 14:16:17,221] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 14:16:43,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 14:16:43,307] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 14:16:46,454] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 14:16:46,458] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 14:16:47,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 75302
[2020-06-29 14:17:37,574] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 224
[2020-06-29 14:17:38,215] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 75302
[2020-06-29 14:23:05,074] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /menu/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:23:05,077] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /menu/ HTTP/1.1" 500 20017
[2020-06-29 14:23:08,408] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:23:08,410] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 20093
[2020-06-29 14:23:11,124] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:23:11,126] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 500 20093
[2020-06-29 14:23:32,949] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /menu/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:23:32,951] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /menu/ HTTP/1.1" 500 20017
[2020-06-29 14:24:01,338] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:24:01,341] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 500 20093
[2020-06-29 14:25:13,450] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 14:25:22,410] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:25:22,416] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:25:22,426] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    self.user, self.auth = user_auth_tuple
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/template/response.py", line 118, in __iter__
    raise ContentNotRenderedError(
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
[2020-06-29 14:25:22,429] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 500 20159
[2020-06-29 14:25:22,429] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 500 20093
[2020-06-29 14:25:22,432] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 500 20165
[2020-06-29 14:28:24,790] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 14:28:54,838] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 14:28:55,079] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 14:28:57,433] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 14:28:57,435] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 14:28:59,356] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 75302
[2020-06-29 14:29:02,813] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 31015
[2020-06-29 14:29:03,748] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 13915
[2020-06-29 14:29:12,632] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:29:54,961] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 259
[2020-06-29 14:29:55,196] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14175
[2020-06-29 14:32:39,266] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14257
[2020-06-29 14:32:39,345] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 14:32:39,345] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 14:32:44,645] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:34:04,922] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 294
[2020-06-29 14:34:05,130] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14552
[2020-06-29 14:34:30,564] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:35:04,030] [log.py:222] [log:log_response] [WARNING]- Conflict: /menu/
[2020-06-29 14:35:04,034] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 409 25
[2020-06-29 14:35:35,128] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 302
[2020-06-29 14:35:35,348] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14858
[2020-06-29 14:40:21,604] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14251
[2020-06-29 14:40:21,638] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 14:40:21,661] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 14:40:32,591] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:42:02,298] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 280
[2020-06-29 14:42:02,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14532
[2020-06-29 14:42:05,517] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:42:22,179] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 280
[2020-06-29 14:42:22,448] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14813
[2020-06-29 14:43:22,181] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14215
[2020-06-29 14:43:22,207] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 14:43:22,221] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 14:43:23,464] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:43:51,960] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 287
[2020-06-29 14:43:52,178] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14503
[2020-06-29 14:43:53,577] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:44:27,709] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 288
[2020-06-29 14:44:28,373] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 14792
[2020-06-29 14:44:29,476] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:44:56,341] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 288
[2020-06-29 14:44:56,555] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 15081
[2020-06-29 14:44:57,771] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/app_list/ HTTP/1.1" 200 25
[2020-06-29 14:45:21,342] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 296
[2020-06-29 14:45:21,594] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 15378
[2020-06-29 14:45:50,614] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 74178
[2020-06-29 14:45:52,168] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 30453
[2020-06-29 14:45:54,895] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/menu/ HTTP/1.1" 200 13353
[2020-06-29 14:45:54,951] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/to_menu/ HTTP/1.1" 200 2298
[2020-06-29 14:46:28,989] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /role/1/assign_menu/ HTTP/1.1" 200 15514
[2020-06-29 14:46:29,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/menu/ HTTP/1.1" 200 15378
[2020-06-29 14:46:29,235] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/to_menu/ HTTP/1.1" 200 2
[2020-06-29 14:46:38,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/menu/ HTTP/1.1" 200 15378
[2020-06-29 14:46:38,017] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/1/to_menu/ HTTP/1.1" 200 2
[2020-06-29 14:46:44,792] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 15378
[2020-06-29 15:03:46,456] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:03:47,358] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:07:27,869] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 15:07:28,007] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:07:28,009] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:11:54,775] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:11:55,771] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:12:02,888] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:12:02,890] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:12:08,154] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:12:08,156] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:12:26,988] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:13:18,425] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:13:28,268] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:13:28,271] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:13:44,442] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:13:45,473] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:13:54,791] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:13:54,794] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:13:59,395] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:13:59,397] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 37
[2020-06-29 15:14:18,135] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:14:19,029] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:14:26,265] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:14:28,764] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:14:28,788] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:14:30,785] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:14:33,512] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 14615
[2020-06-29 15:14:36,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/54/reset_pwd/ HTTP/1.1" 200 28
[2020-06-29 15:14:37,263] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 14580
[2020-06-29 15:17:54,309] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:17:55,129] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:22:55,282] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:22:56,310] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:23:09,371] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:23:10,428] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:23:36,681] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:23:37,777] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:23:55,249] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:23:56,254] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:24:08,342] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:24:09,348] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:24:43,419] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:24:44,391] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:24:48,531] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:24:49,646] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:00,629] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:01,540] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:23,306] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:24,378] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:32,344] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:33,356] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:36,563] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:37,551] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:48,685] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:49,875] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:25:53,262] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:25:54,353] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:26:02,956] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:26:04,028] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:26:09,257] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:26:10,364] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:26:23,627] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:26:24,604] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:26:44,755] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:26:45,846] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:27:03,749] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:27:04,888] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:27:30,237] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 15:27:30,376] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:27:30,377] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 28
[2020-06-29 15:27:37,043] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:27:37,048] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:27:43,416] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:27:43,419] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:27:49,312] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:27:49,314] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:29:46,207] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:29:47,159] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:29:49,125] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:29:49,127] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:30:26,225] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:30:27,118] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:31:48,792] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:31:49,733] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:31:52,312] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:31:56,218] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:31:56,222] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:31:57,874] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:32:00,313] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 14580
[2020-06-29 15:32:04,247] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/54/reset_pwd/ HTTP/1.1" 200 28
[2020-06-29 15:32:04,538] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 14652
[2020-06-29 15:32:13,044] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 32478
[2020-06-29 15:32:17,020] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:32:18,622] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 14652
[2020-06-29 15:32:20,090] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/ HTTP/1.1" 200 32407
[2020-06-29 15:32:24,029] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /user/54/assign_user/ HTTP/1.1" 200 23274
[2020-06-29 15:32:24,380] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 37665
[2020-06-29 15:32:41,852] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:32:42,668] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:32:50,268] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:34:15,354] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:34:15,355] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:34:20,227] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:34:22,301] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=baobao&application=sys&type=menu HTTP/1.1" 301 0
[2020-06-29 15:34:22,303] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=baobao&application=sys&type=button HTTP/1.1" 301 0
[2020-06-29 15:34:22,536] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:34:22,556] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:34:23,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/ HTTP/1.1" 200 15378
[2020-06-29 15:34:26,645] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:36:26,793] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:36:27,624] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:37:34,491] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 219
[2020-06-29 15:37:35,173] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:37:53,909] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 15:37:54,285] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:37:54,287] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:38:02,652] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:38:02,654] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:38:08,410] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:38:08,412] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:38:13,002] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:38:13,004] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:38:33,497] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:38:35,333] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:38:35,334] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:38:36,818] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:39:10,407] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 220
[2020-06-29 15:39:11,111] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:39:22,292] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:39:22,294] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:45:49,812] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:45:49,812] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:45:55,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:45:59,935] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:45:59,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:46:02,561] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:46:32,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 220
[2020-06-29 15:46:33,121] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:46:54,875] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 15:46:54,877] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 15:48:51,865] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 15:48:52,771] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:49:02,024] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 15:49:02,347] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:49:04,694] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:49:04,707] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:49:12,595] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:49:34,376] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 219
[2020-06-29 15:49:35,078] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:50:47,558] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:51:09,671] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 259
[2020-06-29 15:51:10,312] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:51:24,610] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:51:26,299] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=lem&application=sys&type=menu HTTP/1.1" 301 0
[2020-06-29 15:51:26,305] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=lem&application=sys&type=button HTTP/1.1" 301 0
[2020-06-29 15:51:26,478] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=lem&application=sys&type=menu HTTP/1.1" 200 2
[2020-06-29 15:51:26,489] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=lem&application=sys&type=button HTTP/1.1" 200 2
[2020-06-29 15:54:36,167] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 15:54:50,924] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 15:54:53,597] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 15:54:53,619] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=baobao&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 15:54:55,653] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:55:27,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 257
[2020-06-29 15:55:28,120] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 78228
[2020-06-29 15:55:41,679] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:25:20,524] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 16:25:21,338] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:25:25,204] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 16:25:26,100] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:25:48,419] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 16:25:48,767] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:25:51,183] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=lem&application=sys&type=menu HTTP/1.1" 200 2
[2020-06-29 16:25:51,187] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=lem&application=sys&type=button HTTP/1.1" 200 2
[2020-06-29 16:26:05,932] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /user/change_pwd/ HTTP/1.1" 200 28
[2020-06-29 16:26:13,549] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 16:26:13,550] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 28
[2020-06-29 16:26:19,651] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:26:57,434] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 16:26:58,193] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:36:06,670] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 16:36:07,860] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:36:21,740] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-29 16:36:22,661] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:39:42,926] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:40:02,535] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 16:40:02,685] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 16:40:02,686] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 16:40:08,379] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 16:40:08,380] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 16:47:11,417] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:47:27,123] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:47:29,578] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 16:47:29,580] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 16:47:48,355] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /user/change_pwd/
[2020-06-29 16:47:48,357] [basehttp.py:157] [basehttp:log_message] [WARNING]- "PUT /user/change_pwd/ HTTP/1.1" 401 26
[2020-06-29 16:48:29,062] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 79383
[2020-06-29 16:48:57,080] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 256
[2020-06-29 16:48:57,738] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 79383
[2020-06-29 16:49:14,699] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 16:49:14,700] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 28
[2020-06-29 16:49:24,244] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 16:49:24,247] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 28
[2020-06-29 16:49:55,654] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:50:00,842] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:50:33,255] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 16:50:33,564] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 16:50:38,089] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 16:50:38,091] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 16:57:56,192] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-29 16:58:46,707] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:28:05,099] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 17:28:05,241] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 17:28:05,241] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 17:28:11,274] [log.py:222] [log:log_response] [WARNING]- Unauthorized: /auth/
[2020-06-29 17:28:11,276] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /auth/ HTTP/1.1" 401 25
[2020-06-29 17:28:17,895] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:28:57,686] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:29:07,615] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:29:40,927] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:29:42,754] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=gzc&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 17:29:42,758] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=gzc&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 17:29:44,820] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 79671
[2020-06-29 17:29:53,286] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 17:29:56,001] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=wl&application=sys&type=button HTTP/1.1" 200 133
[2020-06-29 17:29:56,011] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=wl&application=sys&type=menu HTTP/1.1" 200 870
[2020-06-29 17:29:57,762] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 79671
[2020-06-29 22:12:27,591] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=wl&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 22:12:27,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=wl&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 22:12:27,603] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=wl&application=monitor&type=menu HTTP/1.1" 301 0
[2020-06-29 22:12:27,607] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=wl&application=monitor&type=button HTTP/1.1" 301 0
[2020-06-29 22:12:27,648] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=wl&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 22:12:27,653] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=wl&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 22:12:28,477] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=wl&application=monitor&type=menu HTTP/1.1" 200 2
[2020-06-29 22:12:28,661] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=wl&application=monitor&type=button HTTP/1.1" 200 2
[2020-06-29 22:12:39,656] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-29 22:12:40,002] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-29 22:12:41,744] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 22:12:41,744] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 22:12:41,755] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=admin&application=monitor&type=button HTTP/1.1" 301 0
[2020-06-29 22:12:41,758] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role?username=admin&application=monitor&type=menu HTTP/1.1" 301 0
[2020-06-29 22:12:41,803] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 0
[2020-06-29 22:12:41,807] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 0
[2020-06-29 22:12:42,204] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 2592
[2020-06-29 22:12:42,222] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 2
[2020-06-29 22:13:25,523] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 2592
[2020-06-29 22:13:25,529] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 2
[2020-06-29 22:13:33,338] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=menu HTTP/1.1" 200 2592
[2020-06-29 22:13:33,339] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=monitor&type=button HTTP/1.1" 200 2
[2020-06-29 22:13:43,970] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=asset&type=menu HTTP/1.1" 200 0
[2020-06-29 22:13:43,970] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role?username=admin&application=asset&type=button HTTP/1.1" 200 0
[2020-06-29 22:13:43,983] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 0
[2020-06-29 22:13:43,998] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 0
[2020-06-29 22:13:44,487] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 6014
[2020-06-29 22:13:44,494] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 60
[2020-06-29 22:14:51,797] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 6014
[2020-06-29 22:14:51,803] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 60
[2020-06-29 22:15:07,643] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 6014
[2020-06-29 22:15:07,646] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 60
[2020-06-29 22:17:41,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=menu HTTP/1.1" 200 1161
[2020-06-29 22:17:41,110] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=sys&type=button HTTP/1.1" 200 291
[2020-06-29 22:17:50,008] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=button HTTP/1.1" 200 60
[2020-06-29 22:17:50,009] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/role/?username=admin&application=asset&type=menu HTTP/1.1" 200 6014
[2020-06-30 10:29:33,803] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
